theme: jekyll-theme-midnight
title: Hello, I am Asif Sharif
description: I am a Full Stack & Cloud developer, currently working on AWS, and also worked with, Azure, Rest Api, .Net Core, Angular, React & React Native.
google_analytics: UA-130067382-1
